# Generated by Django 5.2.3 on 2025-06-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='url',
            field=models.TextField(),
        ),
    ]
